baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "hugo-theme-learn"
enableRobotsTXT = true
googleAnalytics = 'G-NJ4GHWP296'

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[params]
  editURL = "https://github.com/mathieu-benoit/acm-workshop/edit/main/content/"
  description = "Anthos Config Management Workshop - Team 1"
  author = "Mathieu Benoit"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableInlineCopyToClipBoard = true
  themeVariant = "mine"