apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: {{ .Values.name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          image: {{ .Values.container.image.repository }}/{{ .Values.name }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.container.port }}
          resources:
            requests:
              cpu: 5m
              memory: 6Mi
            limits:
              cpu: 15m
              memory: 122Mi
          readinessProbe:
            httpGet:
              port: {{ .Values.container.port }}
              path: /
          livenessProbe:
            tcpSocket:
              port: {{ .Values.container.port }}
          volumeMounts:
          - mountPath: /tmp
            name: tmp
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - emptyDir: {}
        name: tmp
