apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.service.external }}
  type: LoadBalancer
  {{- else }}
  type: ClusterIP
  {{- end }}
  selector:
    app: {{ .Values.name }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}