{{- if .Values.virtualService.create }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.virtualService.host }}
  gateways:
  - {{ .Values.virtualService.gateway.namespace }}/{{ .Values.virtualService.gateway.name }}
  http:
  - route:
    - destination:
        host: {{ .Values.name }}
        port:
          number: {{ .Values.service.port }}
{{- end }}