baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "hugo-theme-relearn"
enableRobotsTXT = true
googleAnalytics = 'G-N4LZTQ74QV'

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[params]
  editURL = "https://github.com/mathieu-benoit/acm-workshop/edit/main/content/"
  description = "ACM/ASM Workshop"
  author = "Mathieu Benoit"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableInlineCopyToClipBoard = false
  disableSearch = true
  themeVariant = "mine"

[[menu.shortcuts]]
  name = "<i class='fab fa-fw fa-github'></i> Release notes"
  url = "https://github.com/mathieu-benoit/acm-workshop/releases"
  weight = 20

[[menu.shortcuts]]
  name = "<i class='fas fa-tags'></i> Tags"
  url = "/tags"
  weight = 30
